#DEBUG: true

MONGO:
  host: 'mongodb://mongodb1.production:27017,mongodb2.production:27017'
  replicaSet: rs0

MONGO_DATABASE: pb

#VARNISH_BASE: 'http://[::1]:8080/'

#CDN_PREFIX: '//d34zelngniy2d8.cloudfront.net'
