apiVersion: v1
kind: Service
metadata:
  labels:
    app: pb
  name: pb
  annotations:
    external_type: http
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10002
  selector:
    app: pb
